# Generated by Django 3.0 on 2019-12-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idd', models.CharField(max_length=150, unique=True)),
                ('title', models.TextField()),
                ('year', models.CharField(max_length=150)),
                ('month', models.CharField(max_length=150)),
                ('vote_average', models.CharField(max_length=150)),
                ('adult', models.TextField()),
                ('popularity', models.CharField(max_length=150)),
                ('belongs_to_collection', models.CharField(max_length=150)),
                ('spoken_languages', models.TextField()),
                ('profit', models.CharField(max_length=150)),
                ('genres', models.TextField()),
                ('original_language', models.TextField()),
                ('original_title', models.TextField()),
                ('production_companies', models.TextField()),
                ('production_countries', models.TextField()),
                ('runtime', models.CharField(max_length=150)),
                ('vote_count', models.CharField(max_length=150)),
                ('revenue', models.CharField(max_length=150)),
                ('animation', models.CharField(max_length=150)),
                ('comedy', models.CharField(max_length=150)),
                ('family', models.CharField(max_length=150)),
                ('adventure', models.CharField(max_length=150)),
                ('fantasy', models.CharField(max_length=150)),
                ('romance', models.CharField(max_length=150)),
                ('drama', models.CharField(max_length=150)),
                ('action', models.CharField(max_length=150)),
                ('crime', models.CharField(max_length=150)),
                ('thriller', models.CharField(max_length=150)),
                ('horror', models.CharField(max_length=150)),
                ('history', models.CharField(max_length=150)),
                ('scienceFiction', models.CharField(max_length=150)),
                ('mystery', models.CharField(max_length=150)),
                ('war', models.CharField(max_length=150)),
                ('foreign', models.CharField(max_length=150)),
                ('music', models.CharField(max_length=150)),
                ('documentary', models.CharField(max_length=150)),
                ('western', models.CharField(max_length=150)),
                ('tvMovie', models.CharField(max_length=150)),
                ('cluster', models.TextField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='portfolio_site',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
