# Generated by Django 3.0 on 2019-12-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0002_auto_20191221_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='cluster',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='idd',
            field=models.CharField(max_length=150),
        ),
    ]
